cron:
  blog: "*/4 * * * * *"
  test: "0 0 24 * * *"
blog:
  type: git
  git:
    url:
    username:
    email:
    token:
    dirpath:
  uploads:
    filename:
    dirs:
      - ""
test:
  type: aliyun-oss
  aliyun-oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
  uploads:
    # no with extension
    filename: "test"
    dirs:
      - "file path"